baseURL = 'https://example.org/'
languageCode = 'en-uk'
title = 'Module Builder'
theme = 'hugo-book'
sectionPagesMenu = 'main'

# From https://gohugo.io/host-and-deploy/host-on-github-pages/
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  custom_css = ["styles.css"]
  BookSection = 'sections'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
